package com.njagakneai.velapdf.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF000000)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE0E3E5)
val md_theme_light_onPrimaryContainer = Color(0xFF191C1E)
val md_theme_light_secondary = Color(0xFF0058BE)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD6E4F7)
val md_theme_light_onSecondaryContainer = Color(0xFF001D40)
val md_theme_light_tertiary = Color(0xFF825500)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDDC1)
val md_theme_light_onTertiaryContainer = Color(0xFF291800)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFF7F9FB)
val md_theme_light_onBackground = Color(0xFF191C1E)
val md_theme_light_surface = Color(0xFFF7F9FB)
val md_theme_light_onSurface = Color(0xFF191C1E)
val md_theme_light_surfaceVariant = Color(0xFFE0E3E5)
val md_theme_light_onSurfaceVariant = Color(0xFF45464D)
val md_theme_light_outline = Color(0xFF76777D)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F3)
val md_theme_light_inverseSurface = Color(0xFF2D3133)
val md_theme_light_inversePrimary = Color(0xFFBEC6E0)

// Optional Dark Theme Colors if requested in future, falling back to light colors for now.
val md_theme_dark_primary = Color(0xFFBEC6E0)
val md_theme_dark_onPrimary = Color(0xFF000000)
val md_theme_dark_primaryContainer = Color(0xFF131B2E)
val md_theme_dark_onPrimaryContainer = Color(0xFFD6E4F7)
val md_theme_dark_secondary = Color(0xFF0058BE)
val md_theme_dark_onSecondary = Color(0xFFFFFFFF)
val md_theme_dark_secondaryContainer = Color(0xFF00387D)
val md_theme_dark_onSecondaryContainer = Color(0xFFD6E4F7)
val md_theme_dark_tertiary = Color(0xFFFFB95F)
val md_theme_dark_onTertiary = Color(0xFF452B00)
val md_theme_dark_tertiaryContainer = Color(0xFF633F00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDC1)
val md_theme_dark_error = Color(0xFFFFDAD6)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1E)
val md_theme_dark_onBackground = Color(0xFFE0E3E5)
val md_theme_dark_surface = Color(0xFF191C1E)
val md_theme_dark_onSurface = Color(0xFFE0E3E5)
val md_theme_dark_surfaceVariant = Color(0xFF45464D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C6CD)
val md_theme_dark_outline = Color(0xFF76777D)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1E)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E5)
val md_theme_dark_inversePrimary = Color(0xFF000000)
